"""Detailed Markdown renderer for the AI repository evidence review.

A pure *packaging* layer: it consumes an already-built VibeExplainerReport (the
Phase 0-7 output) and renders an analyst-reviewable Markdown artifact. It performs
NO analysis of its own — it does not
scan, score, classify, or re-derive anything. Every conclusion it prints comes
straight from the report object, and every important conclusion carries an evidence
reference back to a finding/dataflow/control ID, which is the whole point: this is
what makes the artifact more than an LLM-written "security report."
"""

from __future__ import annotations

from datetime import date
from typing import Any

from . import playbook as _pb
from .security_report import VibeExplainerReport

_SEVERITY_LABEL = {"CRITICAL": "Critical", "HIGH": "High", "MODERATE": "Moderate", "LOW": "Low"}
_LEVEL_NAME = {1: "Baseline", 2: "Managed", 3: "Hardened", 4: "Continuous"}
_CONTROL_STATUS_ORDER = ["DETECTED", "PARTIAL", "NOT_DETECTED", "UNKNOWN", "NOT_APPLICABLE"]


def render_consultant_markdown(report: VibeExplainerReport, *, assessment_date: str | None = None) -> str:
    """Render the detailed analyst-review Markdown artifact.

    assessment_date is the only injected value (defaults to today, UTC-naive). It is
    metadata for the human reader and never affects any analytical content — kept out
    of the underlying report object precisely so report IDs and ordering stay
    deterministic regardless of when the report is rendered.
    """
    m = report.metadata
    es = report.executive_summary
    lines: list[str] = []
    add = lines.append

    # ---- Header -----------------------------------------------------------
    add("# AI Repository Evidence Review")
    add("")
    add("*Generated by Vibe Explainer. Categories use vocabulary adapted from the "
        "HackerOne \"Security for AI: Readiness and Risk Playbook\"; this is not "
        "a HackerOne assessment, endorsement, certification, or validated implementation.*")
    add("")
    add(f"- **Repository:** `{m['repository']}`")
    add(f"- **Assessment date:** {assessment_date or date.today().isoformat()}")
    add(f"- **Engine version:** vibe-explainer {m['version']} (schema {m['schema_version']})")
    add(f"- **Review scope:** Static repository evidence — AI components, attack-surface "
        "leads, inferred relationships, control artifacts, concern scenarios, and process "
        "signals. Does not include runtime testing or adversarial validation.")
    add(f"- **Assessment completeness:** {m['assessment_completeness']}")
    add("")
    add("---")
    add("")

    # ---- Executive summary ------------------------------------------------
    add("## Executive Summary")
    add("")
    if es["ai_surface"] == "NOT_DETECTED":
        add("No supported AI-related signal was detected in the available repository evidence. "
            "Detailed concern and process sections were not generated. This is a coverage-bound "
            "observation, not an assurance that the repository has no AI functionality or is secure.")
        add("")
        _render_limitations(add, report)
        return "\n".join(lines)

    experimental = bool(m.get("experimental_scoring_enabled"))
    highest = es.get("highest_risk_severity")
    level = es.get("readiness_level")
    scenario_mode = "experimental scored" if experimental else "unscored"
    add(f"Supported AI-related repository evidence was detected. The current heuristic policy "
        f"generated **{es['risk_scenario_count']} {scenario_mode} concern scenario(s)**"
        + (
            f", with the highest opt-in experimental severity label being "
            f"**{_SEVERITY_LABEL.get(highest, highest)}**."
            if experimental and highest else "."
        )
        )
    add("")
    add(f"Of **{es['total_findings']}** AI-relevant findings, **{es['production_findings']}** "
        f"are in production code; the remainder are in test, example, documentation, or "
        f"generated content. Findings are labelled by context throughout this report so "
        f"production surface can be distinguished from research and test material.")
    add("")
    defaulted = es.get("defaulted_production_findings", 0)
    if defaulted:
        add(f"> **Context qualification:** **{defaulted}** production finding(s) were classified "
            "as production by conservative default because no stronger path or content signal "
            "was available. Confirm these classifications during analyst review.")
        add("")
    if experimental:
        add("The opt-in experimental process policy produced "
            f"**Level {level} — {_LEVEL_NAME.get(level, es['readiness_name'])}**. This is a "
            "repository-signal classification, not a measurement or certification of security maturity.")
        add("")
    else:
        add("Process artifacts are reported as an **unscored checklist**. Runtime execution, "
            "enforcement, and effectiveness remain **UNKNOWN** in this offline review.")
        add("")
    add("Concern evidence and process-artifact observations are independent. Neither confirms "
        "exploitability, control effectiveness, or the operation of a security process.")
    add("")
    if m["assessment_completeness"] == "PARTIAL":
        add("> ⚠️ **This assessment is INCOMPLETE.** Some files could not be assessed, so the "
            "counts below are a **lower bound** — the correct reading is *\"at least this many\"*, "
            "never *\"only this many.\"* A full assessment requires resolving the gaps noted in "
            "Limitations.")
        add("")
    elif m["assessment_completeness"] == "AGGREGATED":
        add("> **Note:** Some files contained many repeated references to the same component "
            "(e.g. a data-dense retrieval module). These were summarized with **exact counts** — "
            "every match was counted; see the Evidence Appendix for per-group totals. The "
            "assessment is complete.")
        add("")
    add("---")
    add("")

    # ---- AI attack surface ------------------------------------------------
    add("## AI Attack Surface")
    add("")
    add("AI-relevant components discovered in the repository, grouped by the surface they "
        "belong to. Each item references the finding it was derived from and is labelled by "
        "**context** — Production, Test, Example, Documentation, or Generated — so a genuine "
        "production surface can be told apart from test fixtures, demo payloads, and generated "
        "manifests that happen to contain the same strings. Production findings are listed first.")
    add("")
    surface = report.attack_surface
    any_surface = False
    for bucket in ("inputs", "model", "retrieval", "tools", "outputs", "storage"):
        items = surface.get(bucket, [])
        if not items:
            continue
        any_surface = True
        add(f"### {bucket.capitalize()}")
        add("")
        add("| Component | Context | Location | Confidence | Evidence | Finding |")
        add("|---|---|---|---|---|---|")
        # production surface first, then test/example/doc/generated
        ordered = sorted(items, key=lambda i: (0 if i.get("context") == "PRODUCTION" else 1, i["file"], i["line"]))
        for i in ordered:
            add(f"| {i['component']} | {i.get('context', 'PRODUCTION').title()} | `{i['file']}:{i['line']}` | {i['confidence']} | "
                f"{_cell(i['evidence'])} | `{i['finding_id']}` |")
        add("")
    if not any_surface:
        add("No populated attack-surface buckets were detected.")
        add("")
    add("---")
    add("")

    # ---- Data flow --------------------------------------------------------
    add("## Inferred Relationships")
    add("")
    if report.data_flows:
        add("Static relationship observations between AI-related components. These are inferences "
            "from code proximity (same-file) and resolved imports (cross-file) — not "
            "confirmed runtime data flows. The Method column records how each edge was "
            "resolved; cross-file (IMPORT) edges are bounded inference from import "
            "resolution, never proven flow.")
        add("")
        add("| Source | Relationship | Destination | Method | Confidence | Location |")
        add("|---|---|---|---|---|---|")
        for e in report.data_flows:
            method = e.get("resolution_method", "SAME_FILE")
            if method == "IMPORT":
                loc = f"`{e.get('source_file', e['file'])}` → `{e.get('destination_file', e['file'])}`"
            else:
                loc = f"`{e['file']}:{e['source_line']}→{e['destination_line']}`"
            add(f"| {e['source']} | `{e['relationship']}` | {e['destination']} | "
                f"{method} | {e['confidence']} | {loc} |")
        add("")
    else:
        add("No supported static relationships were observed.")
        add("")
    add("---")
    add("")

    # ---- Concern scenarios ------------------------------------------------
    add("## Concern Scenarios")
    add("")
    if experimental:
        add("The explicit experimental option includes an **uncalibrated** 1–25 formula. "
            "These values are deterministic policy outputs, not measured probabilities or "
            "validated vulnerability severities.")
        add("")
        add(f"Formula: `{_pb.RISK_FORMULA}`")
        add("")
        add("| Score | Severity | Playbook readiness |")
        add("|---|---|---|")
        for score_range, severity, readiness_label in _pb.risk_band_table_rows():
            add(f"| {score_range} | {severity} | {readiness_label} |")
    else:
        add("Scenarios are intentionally unscored. Prioritize them through analyst review of "
            "evidence strength, structural reachability, context, and unresolved assumptions.")
    add("")
    if report.risks["scenarios"]:
        for s in report.risks["scenarios"]:
            prefix = f"[{_SEVERITY_LABEL.get(s['severity'], s['severity'])}] " if experimental else ""
            add(f"### {prefix}{s['title']}")
            add("")
            add(f"- **Concern ID:** `{s['risk_id']}`")
            add(f"- **Category:** {s['category']}")
            add(f"- **Evidence strength:** {s['evidence_strength']}")
            add(f"- **Evidence class:** {', '.join(s['evidence_class']) or 'UNSPECIFIED'}")
            add(f"- **Reachability:** {s['reachability_status']}")
            if experimental:
                add(f"- **Experimental score:** {s['score']} / 25 ({s['severity']})")
                e, sa, se, lk = s["exposure"], s["safety_impact"], s["security_exposure"], s["likelihood"]
                add(f"- **Risk factors (playbook):** Experimental inputs — Exposure {e}, Safety {sa}, "
                    f"Security {se}, Likelihood {lk} → ROUND(((({e}+{sa}+{se})/3) × {lk})) = {s['score']}")
            if experimental and s.get("context_adjusted"):
                add(f"- **Context adjustment:** severity capped — this scenario is driven "
                    f"entirely by `{s.get('primary_context', 'non-production')}` code, not "
                    f"production code. The raw score reflects the pattern as if in production.")
            add("- **Unresolved assumptions:** " + " ".join(s["unresolved_assumptions"]))
            add("")
            add(f"{s['rationale']}")
            add("")
            if s["related_control_ids"]:
                add(f"- **Related controls:** {', '.join('`' + c + '`' for c in s['related_control_ids'])}")
            if s["related_finding_ids"]:
                add(f"- **Related findings:** {', '.join('`' + f + '`' for f in s['related_finding_ids'][:8])}"
                    + (" …" if len(s["related_finding_ids"]) > 8 else ""))
            add("")
    else:
        add("No AI security risk scenarios were generated from the available repository evidence. "
            "This does not constitute an assurance that the repository is secure.")
        add("")
    add("---")
    add("")

    # ---- Security controls ------------------------------------------------
    add("## Security Controls")
    add("")
    add("Evidence of security controls found in the repository, classified by the playbook's "
        "control taxonomy — **[P] Preventive**, **[V] Validation**, **[G] Governance**. "
        "**DETECTED** means supporting evidence was found — not that the control is complete, "
        "effective, or resistant to bypass. **NOT_DETECTED** means no supporting evidence was "
        "found — not that the control definitely does not exist (it may live outside this "
        "repository).")
    add("")
    by_status = report.controls["by_status"]
    for status in _CONTROL_STATUS_ORDER:
        controls = by_status.get(status, [])
        if not controls:
            continue
        add(f"### {status.replace('_', ' ').title()}")
        add("")
        add("| Class | Control | Confidence | Rationale |")
        add("|---|---|---|---|")
        for c in sorted(controls, key=lambda c: c["control_id"]):
            cls = _pb.control_class(c["control_id"])
            add(f"| [{cls}] | {c['control_id']} {c['name']} | {c['confidence']} | {_cell(c['rationale'])} |")
        add("")
    add("---")
    add("")

    # ---- Process evidence -------------------------------------------------
    add("## Process-Evidence Checklist")
    add("")
    if experimental:
        lvl_meta = _pb.level_meta(level)
        add(f"**Opt-in experimental policy output: Level {level} — {lvl_meta['name']}**")
        add("")
        add(f"- **Level goal (playbook):** {lvl_meta['goal']}")
        add(f"- **Testing posture:** {lvl_meta['posture']}")
        add(f"- **Typical platform at this level:** {_pb.platform_archetype(level)}")
        add("")
        add("| Level | Name | Status | Missing evidence |")
        add("|---|---|---|---|")
        for la in report.readiness["level_assessments"]:
            missing = la["missing_requirements"][0] if la["missing_requirements"] else ""
            add(f"| {la['level']} | {la['name']} | {la['status']} | {_cell(missing)} |")
        add("")
    else:
        add("Observed repository artifacts are separated from what an offline scan cannot verify. "
            "An observed artifact never changes enforcement from UNKNOWN.")
        add("")
        add("| Check | Artifact status | Enforcement | Missing evidence |")
        add("|---|---|---|---|")
        for check in report.readiness["checks"]:
            missing = check["missing_evidence"][0] if check["missing_evidence"] else ""
            add(f"| {check['name']} | {check['artifact_status']} | "
                f"{check['enforcement_status']} | {_cell(missing)} |")
    add("")
    add("---")
    add("")

    # ---- Top remediations -------------------------------------------------
    add("## Top Remediations")
    add("")
    if report.recommendations:
        for rec in report.recommendations:
            add(f"### {rec['priority']} — {rec['title']}")
            add("")
            add(f"**Why it matters:** {rec['why_it_matters']}")
            add("")
            add(f"**Suggested action:** {rec['suggested_action']}")
            add("")
            refs = []
            if rec["related_risk_ids"]:
                refs.append("risks " + ", ".join("`" + r + "`" for r in rec["related_risk_ids"]))
            if rec["related_control_ids"]:
                refs.append("controls " + ", ".join("`" + c + "`" for c in rec["related_control_ids"]))
            if refs:
                add(f"*Traces to: {'; '.join(refs)}.*")
                add("")
    else:
        add("No remediations were generated.")
        add("")
    add("---")
    add("")

    # ---- Evidence appendix ------------------------------------------------
    add("## Evidence Appendix")
    add("")
    add("Observed AI-related evidence, grouped by category. Every finding above traces to "
        "an entry here by ID.")
    add("")
    if report.ai_inventory.get("truncation_notice"):
        add(f"> **{report.ai_inventory['truncation_notice']}**")
        add("")
    for category, findings in report.ai_inventory["categories"].items():
        add(f"### {category.replace('_', ' ').title()}")
        add("")
        add("| Finding ID | Location | Name | Confidence | Evidence |")
        add("|---|---|---|---|---|")
        for f in findings:
            add(f"| `{f['id']}` | `{f['file']}:{f['line']}` | {f['name']} | {f['confidence']} | {_cell(f['evidence'])} |")
        add("")
    add("---")
    add("")

    # ---- Limitations ------------------------------------------------------
    _render_limitations(add, report)
    return "\n".join(lines)


def _render_limitations(add, report: VibeExplainerReport) -> None:
    add("## Limitations")
    add("")
    add("This review is a static, evidence-based analyst aid, not a guarantee. In particular:")
    add("")
    for lim in report.limitations:
        add(f"- {lim}")
    add("")
    add("This assessment does not prove exploitability, does not confirm that any identified "
        "risk can be successfully exploited, and does not replace adversarial testing or a "
        "manual security review.")


def _cell(text: Any) -> str:
    """Make a string safe for a single Markdown table cell: escape pipes, collapse
    newlines, and trim length so the table stays readable."""
    if text is None:
        return ""
    s = str(text).replace("|", "\\|").replace("\n", " ").strip()
    if len(s) > 160:
        s = s[:157] + "…"
    return s
