"""File context classification (Phase 8C).

Every analyzed file gets a context: PRODUCTION, TEST, SECURITY_TEST, FIXTURE,
EXAMPLE, DEMO, DOCUMENTATION, CONFIGURATION, GENERATED, VENDOR, or UNKNOWN — with a
confidence level and the list of reasons that produced it.

Classification uses multiple signals (path, filename, extension, and optionally file
content) rather than a single directory name, so `tests/test_security.py` becomes
SECURITY_TEST rather than plain TEST, and a security payload in a test is recognized
as test evidence rather than a production vulnerability.

PRODUCTION is the conservative default for a code file with no test/example/doc/
generated signal — under-weighting a real production surface is worse than the
reverse.

This module supersedes the earlier context_classifier.py; that module now re-exports
from here for backward compatibility.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

CONTEXT_PRODUCTION = "PRODUCTION"
CONTEXT_TEST = "TEST"
CONTEXT_SECURITY_TEST = "SECURITY_TEST"
CONTEXT_FIXTURE = "FIXTURE"
CONTEXT_EXAMPLE = "EXAMPLE"
CONTEXT_DEMO = "DEMO"
CONTEXT_DOCUMENTATION = "DOCUMENTATION"
CONTEXT_CONFIGURATION = "CONFIGURATION"
CONTEXT_GENERATED = "GENERATED"
CONTEXT_VENDOR = "VENDOR"
CONTEXT_UNKNOWN = "UNKNOWN"

# Contexts considered "production-relevant" for risk weighting.
PRODUCTION_RELEVANT = frozenset({CONTEXT_PRODUCTION, CONTEXT_CONFIGURATION})

# Security-relevant test contexts — these become positive control evidence, not
# production risk.
SECURITY_EVIDENCE_CONTEXTS = frozenset({CONTEXT_SECURITY_TEST})

CONF_HIGH = "high"
CONF_MODERATE = "moderate"
CONF_LOW = "low"

_DOC_EXTS = {".md", ".mdx", ".rst", ".txt", ".adoc"}
_CONFIG_EXTS = {".yaml", ".yml", ".toml", ".ini", ".cfg", ".env"}
_CONFIG_NAMES = {"dockerfile", "makefile", ".gitignore", ".dockerignore"}

# Security-signal tokens in a filename/path that upgrade a test to SECURITY_TEST.
_SECURITY_TOKENS = re.compile(r"(?i)security|redteam|red[-_]team|adversarial|hardening|exploit|injection|jailbreak|threat|pentest|vuln")

_TEST_PATH = re.compile(r"(?i)(^|/)tests?(/|$)|(^|/)__tests__(/|$)")
_TEST_FILE = re.compile(r"(?i)(^|/)(test_[^/]+|[^/]+_test)\.[a-z0-9]+$|(^|/)[^/]+\.(spec|test)\.[a-z0-9]+$")
_FIXTURE_PATH = re.compile(r"(?i)(^|/)fixtures?(/|$)|(^|/)conftest\.py$|(^|/)__fixtures__(/|$)")
_EXAMPLE_PATH = re.compile(r"(?i)(^|/)(examples?|samples?)(/|$)")
_DEMO_PATH = re.compile(r"(?i)(^|/)demos?(/|$)|(^|/)demo[_-]|[_-]demo\.[a-z0-9]+$")
_DOC_PATH = re.compile(r"(?i)(^|/)docs?(/|$)")
_GENERATED_PATH = re.compile(
    r"(?i)(^|/)(dist|build|out|coverage|node_modules|vendor|\.next|target)(/|$)"
    r"|(^|/)charts?(/|$)"
    r"|(^|/)[^/]*(manifest|graph-ts|graph)\.json$"
    r"|(^|/)[^/]+\.(lock|min\.js|generated\.[a-z0-9]+)$"
    r"|(^|/)package-lock\.json$|(^|/)yarn\.lock$|(^|/)poetry\.lock$"
)
# Content markers that strongly indicate a generated file (checked only if content
# is provided).
_GENERATED_CONTENT = re.compile(r"(?i)@generated\b|do not edit|auto-generated|autogenerated|code generated by")


@dataclass
class FileContext:
    context: str
    confidence: str
    reasons: list[str] = field(default_factory=list)

    @property
    def is_production_relevant(self) -> bool:
        return self.context in PRODUCTION_RELEVANT

    @property
    def is_security_evidence(self) -> bool:
        return self.context in SECURITY_EVIDENCE_CONTEXTS

    def to_dict(self) -> dict:
        return {
            "context": self.context,
            "confidence": self.confidence,
            "reasons": list(self.reasons),
            "is_production_relevant": self.is_production_relevant,
        }


def classify_file(rel_path: str, *, content: str | None = None) -> FileContext:
    """Classify a repository-relative file path (optionally using its content).

    Order matters: the most specific / highest-priority signals are checked first.
    Content is only consulted for a couple of high-value upgrades (security-test
    detection, generated-marker detection) so classification stays cheap.
    """
    p = rel_path.replace("\\", "/")
    lower = p.lower()
    reasons: list[str] = []

    # --- Generated (path or content marker) --------------------------------
    if _GENERATED_PATH.search(p):
        return FileContext(CONTEXT_GENERATED, CONF_HIGH, [f"path matches generated/build/vendor convention: {p}"])
    if content is not None and _GENERATED_CONTENT.search(content[:2000]):
        return FileContext(CONTEXT_GENERATED, CONF_HIGH, ["file content carries a generated-file marker"])

    # --- Documentation -----------------------------------------------------
    ext = "." + lower.rsplit(".", 1)[-1] if "." in lower.rsplit("/", 1)[-1] else ""
    if _DOC_PATH.search(p) or ext in _DOC_EXTS:
        reasons.append("documentation path or extension")
        return FileContext(CONTEXT_DOCUMENTATION, CONF_HIGH, reasons)

    # --- Test family (test / security_test / fixture) ----------------------
    is_test_path = bool(_TEST_PATH.search(p))
    is_test_file = bool(_TEST_FILE.search(p))
    is_fixture = bool(_FIXTURE_PATH.search(p))
    if is_fixture:
        reasons.append("fixture path/conftest")
        # A security-flavored fixture is still security-test evidence.
        if _SECURITY_TOKENS.search(p):
            reasons.append("security token in path")
            return FileContext(CONTEXT_SECURITY_TEST, CONF_MODERATE, reasons)
        return FileContext(CONTEXT_FIXTURE, CONF_HIGH, reasons)
    if is_test_path or is_test_file:
        reasons.append("test path or test filename")
        has_sec_path = _SECURITY_TOKENS.search(p)
        has_sec_content = content is not None and _SECURITY_TOKENS.search(content[:4000])
        if has_sec_path and has_sec_content:
            reasons.append("security token in both path and content")
            return FileContext(CONTEXT_SECURITY_TEST, CONF_HIGH, reasons)
        if has_sec_path:
            reasons.append("security token in path (multi-signal not confirmed by content)")
            return FileContext(CONTEXT_SECURITY_TEST, CONF_MODERATE, reasons)
        return FileContext(CONTEXT_TEST, CONF_HIGH, reasons)

    # --- Example / demo ----------------------------------------------------
    if _DEMO_PATH.search(p):
        return FileContext(CONTEXT_DEMO, CONF_HIGH, ["demo path/filename"])
    if _EXAMPLE_PATH.search(p):
        return FileContext(CONTEXT_EXAMPLE, CONF_HIGH, ["example/sample path"])

    # --- Configuration -----------------------------------------------------
    base = lower.rsplit("/", 1)[-1]
    if ext in _CONFIG_EXTS or base in _CONFIG_NAMES:
        return FileContext(CONTEXT_CONFIGURATION, CONF_MODERATE, [f"configuration extension/name: {base or ext}"])

    # --- Production default -------------------------------------------------
    return FileContext(
        CONTEXT_PRODUCTION,
        CONF_MODERATE,
        ["no test/example/doc/generated signal; treated as production by default"],
    )
