"""Render a ScanResult (+ optional vibe-check notes) into markdown."""

from __future__ import annotations

from typing import Any

from .scanner import ScanResult


def _stack_guess(scan: ScanResult) -> str:
    parts: list[str] = []
    ext = scan.by_ext
    if ext.get(".py"):
        parts.append("Python")
    if ext.get(".ts") or ext.get(".tsx") or ext.get(".js") or ext.get(".jsx"):
        parts.append("JavaScript/TypeScript")
    if ext.get(".go"):
        parts.append("Go")
    if ext.get(".rs"):
        parts.append("Rust")
    if not parts:
        parts.append("mixed / other")
    return ", ".join(parts)


def _start_here(scan: ScanResult) -> list[tuple[str, str]]:
    """Heuristic ordered list of files a newcomer should open first."""
    ordered: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(path: str, reason: str) -> None:
        if path not in seen:
            seen.add(path)
            ordered.append((path, reason))

    for p in scan.readme_paths[:2]:
        add(p, "Project orientation / stated purpose")

    for p in scan.manifests[:3]:
        add(p, "Dependencies and project metadata")

    for p in scan.entry_points[:5]:
        add(p, "Likely application or CLI entry point")

    # largest non-test code files as where the weight is
    for f in scan.largest_files:
        if any(x in f.rel_path.lower() for x in ("test", "spec", "mock", "fixture")):
            continue
        add(f.rel_path, f"Large file ({f.lines} lines) — likely core logic or generated bulk")
        if len(ordered) >= 8:
            break

    return ordered[:8]


def _architecture_mermaid(scan: ScanResult) -> str:
    """Very rough Mermaid sketch from directory shape + entry points."""
    lines = ["```mermaid", "flowchart TD"]
    root_id = "ROOT"
    lines.append(f'  {root_id}["{Path_name(scan.root)}"]')

    # top-level dirs as nodes
    for i, (dirname, count) in enumerate(scan.top_dirs[:8]):
        node = f"D{i}"
        safe = dirname.replace('"', "'")
        lines.append(f'  {node}["{safe} ({count} files)"]')
        lines.append(f"  {root_id} --> {node}")

    if scan.entry_points:
        lines.append('  EP["Entry points"]')
        lines.append(f"  {root_id} --> EP")
        for j, ep in enumerate(scan.entry_points[:5]):
            eid = f"E{j}"
            safe = ep.replace('"', "'")
            lines.append(f'  {eid}["{safe}"]')
            lines.append(f"  EP --> {eid}")

    lines.append("```")
    return "\n".join(lines)


def Path_name(root: str) -> str:
    from pathlib import Path

    return Path(root).name or root


def render_markdown(
    scan: ScanResult,
    *,
    vibe_notes: list[str] | None = None,
    offline: bool = True,
) -> str:
    """Produce the human-readable mental-model report."""
    vibe_notes = vibe_notes or []
    start = _start_here(scan)
    stack = _stack_guess(scan)

    sections: list[str] = []
    sections.append(f"# Mental model: `{Path_name(scan.root)}`")
    sections.append("")
    sections.append(
        f"*Generated by vibe-explainer in "
        f"{'offline' if offline else 'LLM-assisted'} mode. "
        "This is an orientation aid, not a guarantee of correctness.*"
    )
    sections.append("")

    # Overview
    sections.append("## Overview")
    sections.append("")
    overview = (
        f"This repository contains roughly **{scan.total_code_files}** code files "
        f"(~**{scan.total_lines:,}** lines) with a primary stack signal of **{stack}**. "
    )
    if scan.entry_points:
        overview += (
            f"Likely entry points include: "
            + ", ".join(f"`{p}`" for p in scan.entry_points[:4])
            + ". "
        )
    else:
        overview += "No obvious conventional entry points were detected by name. "
    if scan.top_dirs:
        dirs = ", ".join(f"`{d}`" for d, _ in scan.top_dirs[:5])
        overview += f"Top-level concentration: {dirs}."
    sections.append(overview)
    sections.append("")
    sections.append(
        "> Offline mode cannot recover original *intent*. "
        "Treat the above as structural observation only. "
        "Re-run with an LLM layer (when available) for a narrative hypothesis."
    )
    sections.append("")

    # Architecture
    sections.append("## Architecture sketch")
    sections.append("")
    sections.append(_architecture_mermaid(scan))
    sections.append("")
    sections.append(
        "*This diagram is a coarse directory/entry-point map, not a verified "
        "runtime architecture.*"
    )
    sections.append("")

    # Start here
    sections.append("## Start here")
    sections.append("")
    sections.append("Open these in order:")
    sections.append("")
    for i, (path, reason) in enumerate(start, 1):
        sections.append(f"{i}. `{path}` — {reason}")
    if not start:
        sections.append("_No strong start-here candidates found._")
    sections.append("")

    # Key files (largest + entry points)
    sections.append("## Key files (by weight)")
    sections.append("")
    for f in scan.largest_files[:10]:
        sections.append(f"- `{f.rel_path}` — {f.lines} lines")
    sections.append("")

    # Risk / opacity
    sections.append("## Risk & opacity notes")
    sections.append("")
    if vibe_notes:
        sections.append("From linked **vibe-check** report:")
        sections.append("")
        for n in vibe_notes:
            sections.append(f"- {n}")
        sections.append("")
    else:
        sections.append(
            "_No vibe-check report supplied. Run `vibe-check` and pass "
            "`--vibe-check-report` for grounded risk notes._"
        )
        sections.append("")

    # Structural opacity heuristics
    giant = [f for f in scan.largest_files if f.lines >= 800]
    if giant:
        sections.append("Structural signals from this scan:")
        sections.append("")
        for f in giant[:5]:
            sections.append(f"- Large file: `{f.rel_path}` ({f.lines} lines)")
        sections.append("")

    # Suggested questions
    sections.append("## Suggested first questions")
    sections.append("")
    questions = [
        "What is the primary entry point and how does a request / CLI invocation flow from there?",
        "Where is configuration and environment handling defined?",
        "What are the main data models or core domain types?",
        "How are external services / APIs / databases reached?",
        "Which parts look intentionally temporary or experimental?",
    ]
    for q in questions:
        sections.append(f"- {q}")
    sections.append("")

    sections.append("---")
    sections.append(
        f"*vibe-explainer · {scan.total_code_files} files · "
        f"{scan.total_lines:,} lines · stack guess: {stack}*"
    )
    return "\n".join(sections)
